baseURL = 'https://u-d-ash.github.io/Bloggo/'
languageCode = 'en-us'
title = '(u_d) : a blog'
theme = 'custompaper'

disqusShortname = 'bloggo-1'

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['@', '@']]

[params]
defaultTheme = 'dark'
disableThemeToggle = true
math = true
comments = true
disableSpecial1stPost = true



[params.homeInfoParams]
title = "udit jethva"
content = "paint the sky, a shade of hooloovoo !"
imageUrl = "pix.png"


[[menu.main]]
indentifier = "b"
name = "blog"
url = "/blogposts/"
weight = 10

[[menu.main]]
identifier = "d"
name = "gossip"
url = "/konton/"
weight = 20

[[params.socialIcons]]
name = "Linkedin"
url = "https://in.linkedin.com/in/u8d8ash8/"

[[params.socialIcons]]
name = "Instagram"
url = "https://www.instagram.com/u_d_ash_/"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/u-d-ash"
