baseURL = 'http://oyeudiudi.com/'
languageCode = 'en-us'
title = '(u_d) : a blog'
theme = 'custompaper'

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
defaultTheme = 'dark'
disableThemeToggle = true

[params.profileMode]
enabled = true
title = "udit jethva"
subtitle = "paint the sky, a shade of hooloovoo !"
imageTitle = "a good bad boi"
imageUrl = "lmao.png"
imageWidth = 180
imageHeight = 180

[[menu.main]]
identifier = "a"
name = "myself"
url = "/aboutme/"
weight = 5

[[menu.main]]
identifier = "b"
name = "jinsei"
url = "/jinsei/"
weight = 10

[[menu.main]]
identifier = "c"
name = "sugaku"
url = "/sugaku/"
weight = 15

[[params.socialIcons]]
name = "Linkedin"
url = "https://in.linkedin.com/in/u8d8ash8/"

[[params.socialIcons]]
name = "Instagram"
url = "https://www.instagram.com/u_d_ash_/"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/u-d-ash"
